// transform the word list from txt file to golang source file
import fs from 'node:fs';

const argv = process.argv.slice(2);
let input = null;
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === '-i' || a === '--input') {
    input = argv[i + 1];
    i++;
    continue;
  }
  if (a.startsWith('--input=')) input = a.split('=')[1];
}
if (!input) {
  console.error('input is required.');
  process.exit(1);
}
const raw = fs.readFileSync(input, 'utf8');
const words = raw.split('\n').map(w => w.trim()).filter(Boolean);
const header = '// Code generated by mnemonic/word_list/transform.js; DO NOT EDIT.';
const body = `package mnemonic\n\nvar WordList = []string{\n${words.map(w => `\t\"${w}\",`).join('\n')}\n}`;
fs.writeFileSync('word_list.go', `${header}\n${body}\n`);
console.log(`Wrote ${words.length} words to word_list.go`);